### ISSUE TITLE
Copy rewrite

### ISSUE THREAD

**Issue by abibroom** [mysociety/mapit.mysociety.org#7]
Worth a full scrub of all the copy on MapIt, as some of it is out of date (e.g. Land Layer is dead) and much of the rest could be improved (explanation of new account/key stuff) or better arranged (e.g. general information being the _first_ thing on the docs page rather than the last).

**Comment by abibroom** [comment]
Pages:

- [x] homepage; should include #13
- [x] /overview probably unnecessary; new homepage should do this job
- [x] /licensing; should include #27
- [x] /documentation (new page); almost all already exists on homepage, corral a developer to add text for #20

**Comment by abibroom** [comment]
Some bits of the [contract](https://docs.google.com/document/d/1eEkHAJwBlmjUFn1cFvR-XtT6gbouaAYK6vLNr447TiA/edit) that we currently apply to MapIt customers will need to end up on the licensing page.

**Comment by abibroom** [comment]
And possibly we should address https://github.com/mysociety/mapit/issues/83 (although we haven't had one of those requests in ages to my knowledge).

**Comment by MyfanwyNixon** [comment]
Some copy amends for @zarino - contains some queries (feel free to dig in, anyone) and no doubt could also do with some amends from a technical perspective.
https://docs.google.com/document/d/1_VclDzDRG1YEPXLgj_Jje-KpI20uils87VYkxZXiefc/edit#heading=h.n1fke7tfpjzf

**Comment by abibroom** [comment]
Can we do this in a Google doc? Much easier to do suggestions and amendments.

**Comment by MyfanwyNixon** [comment]
NB this hasn't taken into account Abi's recent email about presenting pricing options. mainly because I don't know what we can offer in terms of things like the free trial. However, I could have a bash and then we could strike out anything that looks impractical.

**Comment by zarino** [comment]
> Can we do this in a Google doc? Much easier to do suggestions and amendments.

@abimysoc @MyfanwyNixon: Maybe put it in here, replacing whatever’s currently there (it's all out of date now anyway): https://docs.google.com/document/d/1nztqcKpPFg1_A2xCU8nZvl27KBELQz9gniVPrFK2bLw/edit

**Comment by MyfanwyNixon** [comment]
@abimysoc Ah yes sorry  - https://docs.google.com/document/d/1_VclDzDRG1YEPXLgj_Jje-KpI20uils87VYkxZXiefc/edit

When I got started, I hadn't clocked that I was going to include the long 'non-tech' page which isn't in the top level menu!

**Comment by abibroom** [comment]
Decided this is more or less done, bits that remain are covered by tickets elsewhere.
